#!/usr/bin/env bash
# Story from /etc/passwd using while and IFS

while IFS=: read -r username password uid gid info home shell
do
  echo "The user $username is part of the $username gang, lives in $shell and rides . USER ID's place is protected by the passcode $password, more info about the user here: $username"
done < /etc/passwd
