#!/usr/bin/env bash
# Script telling the story from /etc/passwd

while IFS=':' read -r username password uid gid info home shell
do
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $username"
done < /etc/passwd
