#!/usr/bin/env bash
# Story from /etc/passwd using while and IFS

while IFS=: read -r username password USER ID gid info home shell
do
  echo "The user $username is part of the $gid gang, lives in $home and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $username"
done < /etc/passwd
