#!/usr/bin/env bash
# Bash script manages both files that will be pushed to git
if [ "$1" == "start" ]; then
        chmod +x manage_my_process
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "$1" == "stop" ]; then
    kill "$(cat /var/run/my_process.pid)" 2>/dev/null
    rm -f /var/run/my_process.pid
    echo "manage_my_process stopped"
elif [ "$1" == "restart" ]; then
    kill "$(cat /var/run/my_process.pid)" 2>/dev/null
    rm -f /var/run/my_process.pid
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
