#!/usr/bin/env bash

# Function to handle SIGTERM signal
term_handler() {
  echo "I am invincible!!!"
  exit 0
}

# Trap SIGTERM and call the handler
trap term_handler SIGTERM

# Infinite loop
while true; do
  echo "To infinity and beyond"
  sleep 2
done
